import { Inter } from "next/font/google";
import "./globals.css";
import BootstrapLoader from "@/section/Bootstarp";
import Script from "next/script";
import "../public/assets/css/animate.css";
import "../public/assets/css/all.css";
import "../public/assets/css/bootstrap.min.css";
import "../public/assets/css/boxicons.min.css";
import "../public/assets/css/bootstrap-icons.css";
import "../public/assets/css/swiper-bundle.css";
import "../public/assets/css/style.css";
import Header from "@/section/Header";
import Footer from "@/section/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Silver Line Law",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Load WOW.js for animations */}
        <Script id="wow" src="/js/wow.min.js" strategy="beforeInteractive" />
        {/* Initialize WOW.js */}
        <Script id="initWow" strategy="lazyOnload">
          {`new WOW().init();`}
        </Script>
      </head>
      <body className={inter.className}>
        <BootstrapLoader />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
